# Generated by Django 5.1.2 on 2024-10-15 21:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('postos', '0001_initial'),
        ('vouchers', '0003_voucher_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='GastoVoucher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor_gasto', models.DecimalField(decimal_places=2, max_digits=10)),
                ('data', models.DateTimeField(auto_now_add=True)),
                ('posto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='postos.posto')),
                ('voucher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vouchers.voucher')),
            ],
        ),
    ]
