# Generated by Django 5.1.2 on 2024-10-14 20:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rotas', '0002_rota_valor_total'),
        ('vouchers', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='voucher',
            name='valor',
        ),
        migrations.AddField(
            model_name='voucher',
            name='rota',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='rotas.rota'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='voucher',
            name='valor_restante',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
