# Generated by Django 5.1.2 on 2024-10-15 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vouchers', '0002_remove_voucher_valor_voucher_rota_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='voucher',
            name='status',
            field=models.CharField(default='Pendente', max_length=50),
        ),
    ]
