# Generated by Django 5.1.2 on 2024-10-14 15:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('motoristas', '0001_initial'),
        ('rotas', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='motorista',
            name='rota',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='rotas.rota'),
        ),
    ]
