# Generated by Django 5.1.2 on 2024-10-15 15:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('motoristas', '0002_alter_motorista_rota'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='motorista',
            name='rota',
        ),
    ]
