# Generated by Django 5.1.2 on 2024-10-14 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('postos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rota',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('postos', models.ManyToManyField(to='postos.posto')),
            ],
        ),
    ]
