# Generated by Django 5.1.2 on 2024-11-17 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rotas', '0002_rota_valor_total'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rota',
            name='valor_total',
            field=models.DecimalField(decimal_places=2, default=40.0, max_digits=10),
        ),
    ]
